In [1]:
import numpy as np

# =========================
# Q1
# =========================

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a
corrected_temperature = temperature + 2
print("Corrected temperature:", corrected_temperature)

# b
fahrenheit = (9/5) * corrected_temperature + 32
print("Fahrenheit:", fahrenheit)

# c
greater_than_32 = corrected_temperature[corrected_temperature > 32]
print("Readings > 32°C:", greater_than_32)

# d
count = np.sum(corrected_temperature > 32)
print("Count:", count)


# =========================
# Q2
# =========================

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a
print("\nTotal steps:", np.sum(steps))

# b
print("Mean steps:", np.mean(steps))

# c
print("Maximum:", np.max(steps))
print("Minimum:", np.min(steps))

# d
print("Total per day:", np.sum(steps, axis=0))

# e
print("Total per user:", np.sum(steps, axis=1))

# f
position = np.unravel_index(np.argmax(steps), steps.shape)
print("Maximum position:", position)
print("Maximum value:", steps[position])


# =========================
# Q3
# =========================

# a
original = np.array([1, 2, 3, 4, 5, 6])

# b
subset = original[1:5]

# c
subset[0] = 999

print("\nOriginal:", original)
print("Subset:", subset)

# d
copied = original[1:5].copy()
copied[0] = 500

print("Original after copy:", original)
print("Copied array:", copied)

# e
matrix = np.arange(1, 13).reshape(3, 4)
print("\nMatrix:")
print(matrix)

# f
print("First row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:, 1])
print("Rows 1-2, columns 2-3:")
print(matrix[1:3, 2:4])

# g
flat = matrix.flatten()
ravel = matrix.ravel()

print("Flatten:", flat)
print("Ravel:", ravel)

# h
ravel[0] = 1000
print("\nAfter modifying ravel:")
print("Ravel:", ravel)
print("Matrix:")
print(matrix)

# i
matrix = np.arange(1, 13).reshape(3, 4)
flat = matrix.flatten()

flat[0] = 500

print("\nAfter modifying flatten:")
print("Flatten:", flat)
print("Matrix:")
print(matrix)

# j
print("\nShape:", matrix.shape)
print("ndim:", matrix.ndim)
print("Size:", matrix.size)
print("dtype:", matrix.dtype)


# =========================
# Q4
# =========================

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

# a
print("\nShape of X:", X.shape)
print("Dimensions of X:", X.ndim)

# b
XT = X.T
print("X.T:")
print(XT)

# c
XT_X = X.T @ X
print("X.T @ X:")
print(XT_X)

# d
inverse = np.linalg.inv(XT_X)
print("Inverse:")
print(inverse)

# e
beta = inverse @ X.T @ y
print("Beta:", beta)

# f + g
new_user = np.array([5, 40, 7])

prediction = new_user @ beta

print("Predicted assistance score:", prediction)

Corrected temperature: [27 30 33 37 40 29 35 42]
Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings > 32°C: [33 37 40 35 42]
Count: 5

Total steps: 84200
Mean steps: 7016.666666666667
Maximum: 9500
Minimum: 4500
Total per day: [26500 27300 30400]
Total per user: [18300 24500 14400 27000]
Maximum position: (np.int64(3), np.int64(2))
Maximum value: 9500

Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
Original after copy: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2, columns 2-3:
[[ 7  8]
 [11 12]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel:
Ravel: [1000    2    3    4    5    6    7    8    9   10   11   12]
Matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

After modifying flatten:
Flatten: [500   2   3   4  