In [7]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a+2)
print(a*3)
print(a/2)


[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [6]:
arr = np.array([1,2,3,4,5,6])
print(arr[::-1])

[6 5 4 3 2 1]


In [8]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

# 1. Find the most frequent value
values, counts = np.unique(x, return_counts=True)
most_frequent_value = values[np.argmax(counts)]

# 2. Get all indices where this value occurs
indices = np.where(x == most_frequent_value)[0]

print(f"Most frequent value: {most_frequent_value}")
print(f"Indice(s): {indices.tolist()}")


Most frequent value: 1
Indice(s): [0, 5, 7, 8, 9]


In [10]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
values2,count2 = np.unique(y,return_counts=True)
most_frequent = values2[np.argmax(count2)]
indices2 = np.where(y == most_frequent)[0]
print(f"Most frequent value: {most_frequent}")
print(f"Indice(s): {indices2.tolist()}")

Most frequent value: 1
Indice(s): [0, 1, 2]


In [14]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])

20
70


In [18]:
Nityan = np.linspace(10,101,25)
print(Nityan)
print(Nityan.ndim)
print(Nityan.shape)
print(Nityan.dtype)
print(Nityan.reshape(25,1))

[ 10.          13.79166667  17.58333333  21.375       25.16666667
  28.95833333  32.75        36.54166667  40.33333333  44.125
  47.91666667  51.70833333  55.5         59.29166667  63.08333333
  66.875       70.66666667  74.45833333  78.25        82.04166667
  85.83333333  89.625       93.41666667  97.20833333 101.        ]
1
(25,)
float64
[[ 10.        ]
 [ 13.79166667]
 [ 17.58333333]
 [ 21.375     ]
 [ 25.16666667]
 [ 28.95833333]
 [ 32.75      ]
 [ 36.54166667]
 [ 40.33333333]
 [ 44.125     ]
 [ 47.91666667]
 [ 51.70833333]
 [ 55.5       ]
 [ 59.29166667]
 [ 63.08333333]
 [ 66.875     ]
 [ 70.66666667]
 [ 74.45833333]
 [ 78.25      ]
 [ 82.04166667]
 [ 85.83333333]
 [ 89.625     ]
 [ 93.41666667]
 [ 97.20833333]
 [101.        ]]


In [23]:
ucs420_nityanbhakri = np.array([[10, 20, 30, 40],[50, 60, 70, 80],[90, 15, 20, 35]])
print(ucs420_nityanbhakri.mean())
print(np.median(ucs420_nityanbhakri))
print(ucs420_nityanbhakri.max())
print(ucs420_nityanbhakri.min())
print(np.unique(ucs420_nityanbhakri))
reshaped_ucs420_nityanbhakri = ucs420_nityanbhakri.reshape(4,3)
print(reshaped_ucs420_nityanbhakri)
resized_ucs420_nityanbhakri = ucs420_nityanbhakri.reshape(2,6)
print(resized_ucs420_nityanbhakri)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30 40 50 60]
 [70 80 90 15 20 35]]
